package temp;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import org.json.JSONException;
import org.json.JSONObject;

import com.amap.bean.Fence;
import com.amap.bean.History;
import com.amap.protocol.HTTPUtils;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @AMapCloud
//  @ File Name : FenceHelper.java
//  @ Date : 2016/8/6
//  @ Author : @haifeng.gong hongguang.jin
//
//

public class FenceHelper extends CloudConnection {
	public String tableID = HTTPUtils.FENCE_TABLEID;
	private final static String[] FENCE_FIELD = new String[] { "_id", "_name","_address", "userid1", "userid2", "radius" };

	public FenceHelper() {
		setTableId(tableID);
	}

	public JSONObject parseData(Object data) {
		if (data instanceof Fence) {
			try {
				Fence fence = (Fence) data;
				JSONObject jsonData = new JSONObject();
				jsonData.put(FENCE_FIELD[0], fence.getId());
				jsonData.put(FENCE_FIELD[1], fence.getName());
				jsonData.put(FENCE_FIELD[2], fence.getAddress());
				jsonData.put(FENCE_FIELD[3], fence.getUserId1());
				jsonData.put(FENCE_FIELD[4], fence.getUserId2());
				jsonData.put(FENCE_FIELD[5], fence.getRadius());
				return jsonData;
			} catch (JSONException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				return null;
			}
		}
		return null;
	}

}
