package temp;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import org.json.JSONException;
import org.json.JSONObject;

import com.amap.bean.History;
import com.amap.bean.User;
import com.amap.protocol.HTTPUtils;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @AMapCloud
//  @ File Name : HistoryHelper.java
//  @ Date : 2016/8/6
//  @ Author : @haifeng.gong hongguang.jin
//
//




public class HistoryHelper extends CloudConnection {
	public String tableID=HTTPUtils.HISTORY_TABLEID;
	private final static String[] LOCATION_FIELD = new String[]{"_id","_name","_address","userid"};

	public  HistoryHelper() {
		setTableId(tableID);
	}
	@Override
	public JSONObject parseData(Object data) {
		// TODO Auto-generated method stub
		if (data instanceof History) {
			try {
				History history = (History) data;
				JSONObject jsonData = new JSONObject();
				jsonData.put(LOCATION_FIELD[0], history.getId());
				jsonData.put(LOCATION_FIELD[1], history.getName());
				jsonData.put(LOCATION_FIELD[2], history.getAddress());
				jsonData.put(LOCATION_FIELD[3], history.getUserid());
				return jsonData;
			} catch (JSONException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				return null;
			}
		}
		return null;
	}
}
