package temp;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

import com.amap.bean.User;
import com.amap.protocol.HTTPUtils;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @AMapCloud
//  @ File Name : UserHelper.java
//  @ Date : 2016/8/6
//  @ Author : @haifeng.gong hongguang.jin
//
//

public class UserHelper extends CloudConnection {
	private String tableID = HTTPUtils.USER_TABLEID;
	private final static String[] USER_FIELD = new String[] { "_id", "_name","_address", "userid", "password", "status" };

	public UserHelper() {
		setTableId(tableID);
	}

	public JSONObject parseData(Object data) {
		if (data instanceof User) {
			try {
				User user = (User) data;
				JSONObject jsonData = new JSONObject();
				jsonData.put(USER_FIELD[0], user.getId());
				jsonData.put(USER_FIELD[1], user.getName());
				jsonData.put(USER_FIELD[2], user.getCurrentAddress());
				jsonData.put(USER_FIELD[3], user.getUserId());
				jsonData.put(USER_FIELD[4], user.getUserPassword());
				jsonData.put(USER_FIELD[5], user.getStatus());
				return jsonData;
			} catch (JSONException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				return null;
			}
		}
		return null;
	}
}
